CREATE TABLE [dbo].[Dealers] (
    [ActiveUser]       NVARCHAR(255)   NULL,
    [Address]          NVARCHAR(255)   NULL,
    [City]             NVARCHAR(255)   NULL,
    [CompanyCode]      NVARCHAR(255)   NULL,
    [CustType]         NVARCHAR(255)   NULL,
    [District]         NVARCHAR(255)   NULL,
    [EmailId]          NVARCHAR(255)   NULL,
    [FirstName]        NVARCHAR(255)   NULL,
    [GstCode]          NVARCHAR(255)   NULL,
    [GstNumber]        NVARCHAR(255)   NULL,
    [Location]         NVARCHAR(255)   NULL,
    [PanNumber]        NVARCHAR(255)   NULL,
    [Password]         NVARCHAR(255)   NULL,
    [Phone]            NVARCHAR(255)   NULL,
    [Place]            NVARCHAR(255)   NULL,
    [plantName]        VARCHAR(255)    NULL,
    [PostalCode]       NVARCHAR(255)   NULL,
    [PriceGroup]       NVARCHAR(255)   NULL,
    [PriceList]        NVARCHAR(255)   NULL,
    [RegionName]       NVARCHAR(255)   NULL,
    [SalesOrg]         NVARCHAR(255)   NULL,
    [SatelliteUser]    NVARCHAR(255)   NULL,
    [StateCode]        NVARCHAR(255)   NULL,
    [UserName]         NVARCHAR(255)   NULL,
    [UserType]         NVARCHAR(255)   NULL
);
